name: pywwt

channels:
  - conda-forge

dependencies:
  - python>=3
  - traitlets
  - ipywidgets>=7.0
  - astropy
  - qtpy
  - pyqt
  - widgetsnbextension
  - ipyevents
  - nomkl
  - nodejs
  - matplotlib
  - beautifulsoup4
  - lxml
  - python-dateutil
  - pip:
    - sphinx-automodapi
    - numpydoc
