[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cranko]
main_version_file = "pywwt/_version.py"
annotated_files = ["pywwt/jupyter.py"]

[tool.cranko.internal_dep_versions]
"npm:pywwt" = "thiscommit:2023-09-15:VaRzh3C"
